#!/usr/bin/env python3
"""Generate and verify the derived Gemini Notebook Bundle and manifest.

The individual RAW files remain the canonical records. This script reads the
RAW file order from INDEX.md and copies each file's bytes verbatim into the
bundle; it never summarizes or rewrites RAW content.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "INDEX.md"
BUNDLE = ROOT / "GEMINI_NOTEBOOK_BUNDLE.md"
MANIFEST = ROOT / "NOTEBOOK_SYNC_MANIFEST.md"


def git(*args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()


def target_files() -> list[Path]:
    """Return INDEX-listed RAW Markdown files in their documented order."""
    targets: list[Path] = []
    for line in INDEX.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^- ([^\s（(]+\.md)", line)
        if not match:
            continue
        name = match.group(1)
        if not name.endswith("_RAW.md"):
            continue
        path = ROOT / name
        if not path.is_file():
            raise FileNotFoundError(f"INDEX.md lists a missing RAW file: {name}")
        targets.append(path)
    if not targets:
        raise RuntimeError("No INDEX-listed *_RAW.md files found")
    return targets


def source_commit() -> str:
    return os.environ.get("GEMINI_BUNDLE_SOURCE_COMMIT") or git("rev-parse", "HEAD")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def build_bundle(files: list[Path], commit: str) -> tuple[bytes, list[tuple[Path, bytes]]]:
    parts = [
        "<!-- DO NOT EDIT: generated from INDEX-listed RAW files. -->\n"
        "GitHubの個別RAWが正本。Bundleは派生物であり、要約ではなく原文連結です。\n"
        "各区切りの後の原文部分は、対応するRAWファイルのバイト列をそのまま収録しています。\n\n"
    ]
    raw_data: list[tuple[Path, bytes]] = []
    output = "".join(parts).encode("utf-8")
    for path in files:
        data = path.read_bytes()
        raw_data.append((path, data))
        header = (
            f"===== FILE: {path.name} =====\n"
            f"Source commit SHA: {commit}\n"
            f"Source SHA-256: {sha256(data)}\n"
            "===== BEGIN RAW (verbatim) =====\n"
        ).encode("utf-8")
        output += header + data
        if not data.endswith(b"\n"):
            output += b"\n"
        output += b"===== END RAW =====\n\n"
    return output, raw_data


def build_manifest(files: list[Path], raw_data: list[tuple[Path, bytes]], commit: str) -> bytes:
    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    lines = [
        "<!-- DO NOT EDIT: generated by scripts/generate_gemini_notebook_bundle.py -->",
        "GitHubの個別RAWが正本。これは同期状態確認用の派生Manifestで、内容要約は含みません。",
        "",
        f"- Current GitHub commit: `{commit}`",
        f"- Bundle generation commit: `{commit}`",
        f"- Generated at (UTC): `{generated_at}`",
        f"- Target file count: **{len(files)}**",
        "",
        "## 対象ファイル（INDEX.md記載順）",
        "",
        "| # | File | Source commit SHA | Bytes | SHA-256 |",
        "|---:|---|---|---:|---|",
    ]
    for index, (path, data) in enumerate(raw_data, 1):
        lines.append(f"| {index} | `{path.name}` | `{commit}` | {len(data)} | `{sha256(data)}` |")
    lines.extend([
        "",
        "Bundleは上記ファイルを同じ順序で原文連結した生成物です。",
        "要約ファイルとテスト用ファイルは対象外です。",
        "",
    ])
    return ("\n".join(lines)).encode("utf-8")


def generate() -> None:
    files = target_files()
    commit = source_commit()
    bundle, raw_data = build_bundle(files, commit)
    BUNDLE.write_bytes(bundle)
    MANIFEST.write_bytes(build_manifest(files, raw_data, commit))


def verify() -> None:
    files = target_files()
    # After the generated files are committed, HEAD is the generated commit,
    # while the bundle records the source commit that was used to build it.
    recorded_commit = re.search(r"^- Current GitHub commit: `([^`]+)`$", MANIFEST.read_text(encoding="utf-8"), re.MULTILINE) if MANIFEST.exists() else None
    commit = source_commit() if os.environ.get("GEMINI_BUNDLE_SOURCE_COMMIT") else (recorded_commit.group(1) if recorded_commit else git("rev-parse", "HEAD"))
    expected_bundle, raw_data = build_bundle(files, commit)
    if not BUNDLE.is_file() or BUNDLE.read_bytes() != expected_bundle:
        raise AssertionError("Bundle differs from the verbatim INDEX-listed RAW concatenation")
    manifest = MANIFEST.read_text(encoding="utf-8")
    if f"- Target file count: **{len(files)}**" not in manifest:
        raise AssertionError("Manifest target count does not match INDEX-listed RAW files")
    positions = [manifest.find(f"`{path.name}`") for path in files]
    if any(pos < 0 for pos in positions) or positions != sorted(positions):
        raise AssertionError("Manifest file list is missing a file or has the wrong order")
    for path, data in raw_data:
        digest = sha256(data)
        if f"`{digest}`" not in manifest:
            raise AssertionError(f"Manifest is missing SHA-256 for {path.name}")
        if f"Source SHA-256: {digest}".encode() not in BUNDLE.read_bytes():
            raise AssertionError(f"Bundle is missing SHA-256 for {path.name}")
    bundle_bytes = BUNDLE.read_bytes()
    marker_positions = [bundle_bytes.find(f"===== FILE: {path.name} =====\n".encode()) for path in files]
    if any(position < 0 for position in marker_positions) or marker_positions != sorted(marker_positions):
        raise AssertionError("Bundle file markers do not match INDEX order")
    print(f"verified {len(files)} RAW files; order, byte concatenation, and SHA-256 values match")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true", help="verify existing generated files")
    args = parser.parse_args()
    verify() if args.verify else generate()


if __name__ == "__main__":
    main()
